Update merge in main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -137,5 +137,8 @@ jobs:
             git fetch origin rabbitmq:rabbitmq  # Récupération explicite de la branche dev
             git merge -X theirs rabbitmq
             git push origin main
+          else
+            echo "Tests failed, skipping merge."
+            exit 1
           fi
 
